package com.marcogn.coverdex.domain.repository

import com.marcogn.coverdex.domain.model.TeamMember
import kotlinx.coroutines.flow.Flow

interface CustomPokemonRepository {

    val roster: Flow<List<TeamMember>>

    /** Upserts by [TeamMember.id] — an id already in the roster is an edit, any other id a new
     * entry. Ids are generated by the caller (the slot editor's "Save to roster" action reuses
     * the slot's own member id; the roster screen's own editor generates a fresh one). */
    suspend fun save(member: TeamMember)

    suspend fun delete(id: String)
}
